# General Setting
set -g mouse on
set -g mode-keys vi


# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @yank_with_mouse off
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'laktak/extrakto'
set -g @plugin 'b0o/tmux-autoreload'
set -g @plugin 'tmux-plugins/tmux-cpu'


# Catppuccin Themes
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "basic"
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_status_connect_separator "yes"
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
set -g status-right-length 160
set -g status-left-length 0
set -g status-left ""
set -g status-justify left
set -g status-right "#{E:@catppuccin_status_directory}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -agF status-right "#{E:@catppuccin_status_ram}"
set -ag status-right "#{E:@catppuccin_status_session}"

# TPM
run '~/.tmux/plugins/tpm/tpm'
